// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginOutput struct {
	Name     string `json:"name"`
	Token    string `json:"token"`
	Expires  int    `json:"expires"`
	Path     string `json:"path"`
	Domain   string `json:"domain"`
	Secure   bool   `json:"secure"`
	HTTPOnly bool   `json:"httpOnly"`
}

type Source struct {
	Name   string `json:"name"`
	Schema string `json:"schema"`
}
