// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: grpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScorifyClient is the client API for Scorify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScorifyClient interface {
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type scorifyClient struct {
	cc grpc.ClientConnInterface
}

func NewScorifyClient(cc grpc.ClientConnInterface) ScorifyClient {
	return &scorifyClient{cc}
}

func (c *scorifyClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, "/proto.Scorify/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScorifyServer is the server API for Scorify service.
// All implementations must embed UnimplementedScorifyServer
// for forward compatibility
type ScorifyServer interface {
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	mustEmbedUnimplementedScorifyServer()
}

// UnimplementedScorifyServer must be embedded to have forward compatible implementations.
type UnimplementedScorifyServer struct {
}

func (UnimplementedScorifyServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedScorifyServer) mustEmbedUnimplementedScorifyServer() {}

// UnsafeScorifyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScorifyServer will
// result in compilation errors.
type UnsafeScorifyServer interface {
	mustEmbedUnimplementedScorifyServer()
}

func RegisterScorifyServer(s grpc.ServiceRegistrar, srv ScorifyServer) {
	s.RegisterService(&Scorify_ServiceDesc, srv)
}

func _Scorify_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScorifyServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scorify/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScorifyServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scorify_ServiceDesc is the grpc.ServiceDesc for Scorify service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scorify_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Scorify",
	HandlerType: (*ScorifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Scorify_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
