// Code generated by scorify, DO NOT EDIT.
// Import generated from "github.com/scorify/web@v1.0.0"

package checks

import (
	web "github.com/scorify/web"
)

func init() {
	Checks["web"] = Check{
		Func:   web.Run,
		Schema: ConvertSchema(web.Schema{}),
	}
}